### ISSUE TITLE
Docs should clarify that RANGE is inclusive 

### ISSUE THREAD

**Issue by comorbidity** [smart-on-fhir/chart-review#57]
https://docs.smarthealthit.org/cumulus/chart-review/config.html

Example 
```
ranges:
  amy: 782-894
  andy: 895-1006
  alon: [992, 993, 994, 995, 996, 997, 998, 999, 1000, 1001, 1002, 1003, 1004, 1005, 979, 980, 981, 982, 983, 984, 985, 986, 987, 988, 989, 990, 991, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889, 890]
```

it was not obvious that Range should not include the final number, 
  amy: 782-894 VS 
  amy: 782-895

```
Python 
max(range(782,895)) 
= 894
```
